version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./django/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db

  django_gunicorn:
    image: gunicorn
    build: 
      context: ./django
    volumes:
      - ./django:/usr/src/django_app
      - media_files:/usr/src/django_app/media
    env_file:
      - ./django/.env
    expose:
      - 8000
    # ports:
    #   - "8000:8000"
    depends_on:
      - db
    container_name: gunicorn_container
  
  nginx:
    image: nginx
    build: ./nginx
    volumes:
      - media_files:/mediafiles/usr/src/django_app/media
      # mimicking the directory stucture to img.url 
    ports:
      - 80:80
    depends_on:
      - django_gunicorn
    container_name: nginx_container

volumes:
  media_files:
